### ISSUE TITLE
Channel intended for Mature audience warning instead of channel preview

### ISSUE THREAD

**Issue by kaefs** [MarkM-dev/Twitch-Previews#79] opened 2022-08-07 19:04 UTC
Getting the black screen ([example](https://imgur.com/J2cByz6)) where you click to confirm you are of age to watch a stream instead of the channel preview when hovering over both the directory and sidebar. I have already confirmed I am of age by clicking "start watching" on a channel page but the warning page still shows on the channels that have it enabled when I try to preview it. I don't get this warning page when actually on a channel watching actively, only when trying to preview channels. I have also refreshed and closed/reopened the browser. The issue only started after disabling this extension and reenabling it. Image preview is fine though.

**Comment by MarkM-dev** [comment] 2022-08-08 09:29
its due to recent twitch changes.
duplicate of https://github.com/MarkM-dev/Twitch-Previews/issues/73
don't have a solution for now, when i have time to work on i ill try to fix it.

**Closed by MarkM-dev** 2022-08-08 09:29 UTC

**Comment by MarkM-dev** [comment] 2022-08-12 13:38
so here's the issue:
- twitch don't sync the "mature" flag in the local storage between their sub domains (www.twitch.tv and player.twitch.tv).
so if you click on "start watching" button on the mature content message on www.twitch.tv, it won't affect player.twitch.tv (which is the preview).
- You only need to click it once (unless you change computers or use incognito or somehow lose your browser's local storage for these domains).

Fix for now until i find a way to make this more user friendly:
when you encounter a preview with a mature content warning:
1. disable advanced video embeds (if you have it enabled).
2. open the streamer with the mature content in an embed (drag and drop the streamer from the sidebar onto the page or click the 4 squares button under the view count on the sidebar).
3. click the "start watching" button.
4. close the embed.
5. enable advanced video embeds (if you had it enabled).
